sudo systemctl $1 open5gs-mmed
sudo systemctl $1 open5gs-sgwcd
sudo systemctl $1 open5gs-smfd
sudo systemctl $1 open5gs-amfd
sudo systemctl $1 open5gs-sgwud
sudo systemctl $1 open5gs-upfd
sudo systemctl $1 open5gs-hssd
sudo systemctl $1 open5gs-pcrfd
sudo systemctl $1 open5gs-nrfd
sudo systemctl $1 open5gs-scpd
sudo systemctl $1 open5gs-ausfd
sudo systemctl $1 open5gs-udmd
sudo systemctl $1 open5gs-pcfd
sudo systemctl $1 open5gs-nssfd
sudo systemctl $1 open5gs-bsfd
sudo systemctl $1 open5gs-udrd
sudo systemctl $1 open5gs-webui
